### ISSUE TITLE
Input events API discussion

### ISSUE THREAD

**Issue by sniok** [react-spring/react-xr#1]
I can see two types of events that would be usefull in xr apps:
1. Events that can be attached to ingame objects (e.g.:  hovering a button)
2. 'Standalone' events (e.g: trigger press)

For standalone events I think this should be straightforward, exposing a hook like this:
```
useXREvent(() => console.log('pew!'), { type: "select", handedness: "left" }); 
```

Now for events attached to objects I have few ideas

hooks could look something like this:
```jsx
const ref1 = useXRInput("pointerover", () => setHover(true));
const ref2 = useXRInput("pointerout", () => setHover(false));

<mesh ref={mergeRefs([ref1, ref2])} />
```
or to limit amount of refs it may look like this: 

```jsx
const ref = useXRInputs({
  'pointerover': () => ...
  'pointerout': () => ...
})

<mesh ref={ref} />
```

but I also propose to expose more high level components to handle events

```jsx
<Hover onChange={value => setHover(value)}>
  <mesh />
</Hover>
```

and under the hood inside those components attach events to the threejs `group` object

what do you think?

**Comment by drcmda** [comment]
@sniok i think you could go either way and see how it feels in practice. i like the second one better myself but then again i lack vr experience so i dont feel i should have much say

**Comment by sniok** [comment]
Component based event listeners work fine so far. If you have better ideas or want to discuss this further please open an issue. Closing this one as it seems dead
